language: php

matrix:
  include:
    - php: 5.3
      env: PHP_VER=5
    - php: 5.4
      env: PHP_VER=5
    - php: 5.5
      env: PHP_VER=5
    - php: 5.6
      env: PHP_VER=5
    - php: 7.0
      env: PHP_VER=7
    - php: hhvm
      env: PHP_VER=hhvm
    - php: nightly
      env: PHP_VER=7
  allow_failures:
    - php: 7.0
    - php: nightly

install:
  - composer install --no-interaction --prefer-dist

before_script:
  - if [ $PHP_VER = "5" ]; then phpenv config-add myconfig.ini; fi

script:
  - phpunit
  - sh -c "./vendor/bin/phpcs --standard=PSR2 ./src/"

services:
  - redis-server