language: php

matrix:
  include:
    - php:
      - 5.3
      - 5.4
      - 5.5
      - 5.6
      env: PHP_VER=5
    - php:
      - 7.0
      - nightly
      env: PHP_VER=7
    - php:
      - hhvm
      env: PHP_VER=hhvm

install:
  - composer install --no-interaction --prefer-dist

before_script:
  - if [$PHP_VER = "5"]; then phpenv config-add myconfig.ini fi

script:
  - phpunit
  - sh -c "./vendor/bin/phpcs --standard=PSR2 ./src/"

services:
  - redis-server