language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

install:
  - composer install --no-interaction --prefer-dist

script:
  - phpunit
  - sh -c "./vendor/bin/phpcs --standard=PSR2 ./src/"

services:
  - redis-server