language: php

matrix:
  include:
    - php: 5.3
      env: PHP_VER=5
    - php: 5.4
      env: PHP_VER=5
    - php: 5.5
      env: PHP_VER=5
    - php: 5.6
      env: PHP_VER=5
    - php: 7.0
      env: PHP_VER=7
    - php: hhvm
      env: PHP_VER=hhvm
    - php: nightly
      env: PHP_VER=7
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - composer install --no-interaction --prefer-dist

before_script:
  - phpenv config-add phpconfig.ini

script:
  - phpunit --coverage-clover=coverage.xml
  - sh -c "./vendor/bin/phpcs --standard=PSR2 ./src/"

after_success:
    - bash <(curl -s https://codecov.io/bash)

services:
  - redis-server
